library(dplyr)

setwd('C:/Users/haras_000/Desktop/Neuroleptyki/Programy')

# Read data
df_1 <- read.csv('../Dane/nasercowe_1.csv', sep=';')
df_2 <- read.csv('../Dane/nasercowe_2.csv', sep=';')
df_3 <- read.csv('../Dane/nasercowe_3.csv', sep=';')

# Concatenate data
df <- rbind(df_1, df_2, df_3)

# Remove unnecessary variables - free memory
df_1 <- NULL
df_2 <- NULL
df_3 <- NULL

# Fix coding issue with polish characters
df$P.³eæ...nazwa <- replace(as.character(df$P.³eæ...nazwa),
                                      df$P.³eæ...nazwa=='m©¾czyzna',
                                      'mezczyzna')

# Data cleaning
buyers_age <- as.integer(format(as.POSIXct(df$Data.realizacji.recepty), format='%Y')) - as.integer(as.character(df$Data.urodzenia..rok.))
df_right_age <- subset(df, buyers_age >= 3)
buyers_death <- as.character(df_right_age$Data.zgonu..rok.miesi¹c.)
buyers_death <- replace(buyers_death, buyers_death=='', '2014-10')
df_right_age <- subset(df_right_age, as.character(df_right_age$Data.realizacji.recepty) < paste(buyers_death, '32', sep='-'))

# Unified units in Dose/Dawka field
unified_dose <- as.character(df_right_age$Dawka)
unified_dose <- replace(unified_dose, unified_dose=='400 mg', '0.4')
unified_dose <- replace(unified_dose, unified_dose=='4%', '0.04')
unified_dose <- replace(unified_dose, unified_dose=='0,5 MG', '0.0005')
unified_dose <- replace(unified_dose, unified_dose=='0,405 G', '0.405')
unified_dose <- replace(unified_dose, unified_dose=='0,4 G', '0.4')
unified_dose <- replace(unified_dose, unified_dose=='0,3 G', '0.3')
unified_dose <- replace(unified_dose, unified_dose=='0,25 G', '0.25')
unified_dose <- replace(unified_dose, unified_dose=='0,21 G', '0.21')
unified_dose <- replace(unified_dose, unified_dose=='0,2%', '0.002')
unified_dose <- replace(unified_dose, unified_dose=='0,2 G/1 ML', '0.2')
unified_dose <- replace(unified_dose, unified_dose=='0,2 G', '0.2')
unified_dose <- replace(unified_dose, unified_dose=='0,15 G', '0.15')
unified_dose <- replace(unified_dose, unified_dose=='0,2 G', '0.2')
unified_dose <- replace(unified_dose, unified_dose=='0,1 G/5 ML', '0.1')
unified_dose <- replace(unified_dose, unified_dose=='0,15 G', '0.15')
unified_dose <- replace(unified_dose, unified_dose=='0,1 G/2 ML', '0.1')
unified_dose <- replace(unified_dose, unified_dose=='0,1 G/1 ML', '0.1')
unified_dose <- replace(unified_dose, unified_dose=='0,1 G', '0.1')
unified_dose <- replace(unified_dose, unified_dose=='0,08 G', '0.08')
unified_dose <- replace(unified_dose, unified_dose=='0,06 G', '0.06')
unified_dose <- replace(unified_dose, unified_dose=='0,05 G/1 ML', '0.05')
unified_dose <- replace(unified_dose, unified_dose=='0,05 G', '0.05')
unified_dose <- replace(unified_dose, unified_dose=='0,04 G/2 ML', '0.04')
unified_dose <- replace(unified_dose, unified_dose=='0,04 G', '0.04')
unified_dose <- replace(unified_dose, unified_dose=='0,0375 G', '0.0375')
unified_dose <- replace(unified_dose, unified_dose=='0,025 G/5 ML', '0.025')
unified_dose <- replace(unified_dose, unified_dose=='0,025 G/1 ML', '0.025')
unified_dose <- replace(unified_dose, unified_dose=='0,025 G', '0.025')
unified_dose <- replace(unified_dose, unified_dose=='0,02 G', '0.02')
unified_dose <- replace(unified_dose, unified_dose=='0,02 G/1 ML', '0.02')
unified_dose <- replace(unified_dose, unified_dose=='0,016 G', '0.016')
unified_dose <- replace(unified_dose, unified_dose=='0,015 G', '0.015')
unified_dose <- replace(unified_dose, unified_dose=='0,012 G', '0.012')
unified_dose <- replace(unified_dose, unified_dose=='0,01 G', '0.01')
unified_dose <- replace(unified_dose, unified_dose=='0,008 G', '0.008')
unified_dose <- replace(unified_dose, unified_dose=='0,0075 G', '0.0075')
unified_dose <- replace(unified_dose, unified_dose=='0,005 G/1 ML', '0.005')
unified_dose <- replace(unified_dose, unified_dose=='0,005 G', '0.005')
unified_dose <- replace(unified_dose, unified_dose=='0,004 G', '0.004')
unified_dose <- replace(unified_dose, unified_dose=='0,003 G', '0.003')
unified_dose <- replace(unified_dose, unified_dose=='0,002 G', '0.002')
unified_dose <- replace(unified_dose, unified_dose=='0,001 G/1 ML', '0.001')
unified_dose <- replace(unified_dose, unified_dose=='0,001 G', '0.001')

unified_dose <- replace(unified_dose, unified_dose=='0,1 MG', '0.0001')
unified_dose <- replace(unified_dose, unified_dose=='0,03 G', '0.03')
unified_dose <- replace(unified_dose, unified_dose=='0,0125 G', '0.0125')
unified_dose <- replace(unified_dose, unified_dose=='0,85 G', '0.85')
unified_dose <- replace(unified_dose, unified_dose=='300 J.M./3 ML', '300')
unified_dose <- replace(unified_dose, unified_dose=='0,5 G', '0.5')
unified_dose <- replace(unified_dose, unified_dose=='0,0015 G', '0.0015')
unified_dose <- replace(unified_dose, unified_dose=='0,0025 G', '0.0025')
unified_dose <- replace(unified_dose, unified_dose=='0,09 G', '0.09')
unified_dose <- replace(unified_dose, unified_dose=='0,00625 G', '0.00625')
unified_dose <- replace(unified_dose, unified_dose=='1 G', '1.0')
unified_dose <- replace(unified_dose, unified_dose=='0,12 G', '0.12')
unified_dose <- replace(unified_dose, unified_dose=='0,267 G', '0.267')
unified_dose <- replace(unified_dose, unified_dose=='0,00125 G', '0.00125')
unified_dose <- replace(unified_dose, unified_dose=='0,00625 G', '0.00625')
unified_dose <- replace(unified_dose, unified_dose=='0,24 G', '0.24')
unified_dose <- replace(unified_dose, unified_dose=='0,02375 G BURSZTYNIANU = 0,025 G WINIANU', '0.025')
unified_dose <- replace(unified_dose, unified_dose=='0,16 G', '0.16')
unified_dose <- replace(unified_dose, unified_dose=='0,25%', '0.0025')
unified_dose <- replace(unified_dose, unified_dose=='0,25 MG', '0.00025')
unified_dose <- replace(unified_dose, unified_dose=='0,18 G', '0.18')
unified_dose <- replace(unified_dose, unified_dose=='0,5%', '0.005')
unified_dose <- replace(unified_dose, unified_dose=='0,6 G', '0.6')
unified_dose <- replace(unified_dose, unified_dose=='0,075 G', '0.075')
unified_dose <- replace(unified_dose, unified_dose=='0,00125 G W DAWCE', '0.00125')
unified_dose <- replace(unified_dose, unified_dose=='0,006 G', '0.006')
unified_dose <- replace(unified_dose, unified_dose=='0,0475 G BURSZTYNIANU = 0,05 G WINIANU', '0.05')
unified_dose <- replace(unified_dose, unified_dose=='0,003125 G', '0.003125')
unified_dose <- replace(unified_dose, unified_dose=='0,16 G + 0,025 G', '0.185')
unified_dose <- replace(unified_dose, unified_dose=='0,02 G/2 ML', '0.02')
unified_dose <- replace(unified_dose, unified_dose=='800 J.M./10 ML', '800')
unified_dose <- replace(unified_dose, unified_dose=='0,05 G + 0,0125 G', '0.0625')
unified_dose <- replace(unified_dose, unified_dose=='0,215 G', '0.215')
unified_dose <- replace(unified_dose, unified_dose=='0,08 G + 0,0125 G', '0.0925')
unified_dose <- replace(unified_dose, unified_dose=='5 MG + 0,0125 G', '0.0175')
unified_dose <- replace(unified_dose, unified_dose=='5 MG + 1,25 MG', '0.00625')
unified_dose <- replace(unified_dose, unified_dose=='5 MG + 25 MG', '0.03')
unified_dose <- replace(unified_dose, unified_dose=='50 mg', '0.05')
unified_dose <- replace(unified_dose, unified_dose=='4 MG + 1,25 MG', '0.00525')
unified_dose <- replace(unified_dose, unified_dose=='50 MG + 12,5 MG', '0.0625')
unified_dose <- replace(unified_dose, unified_dose=='100 MG + 25 MG', '0.125')
unified_dose <- replace(unified_dose, unified_dose=='160 MG + 12,5 MG', '0.1725')
unified_dose <- replace(unified_dose, unified_dose=='80 MG + 25 MG', '0.105')
unified_dose <- replace(unified_dose, unified_dose=='2,5 MG + 12,5 MG', '0.015')
unified_dose <- replace(unified_dose, unified_dose=='160 MG + 25 MG', '0.185')
unified_dose <- replace(unified_dose, unified_dose=='10 MG + 5 MG', '0.015')
unified_dose <- replace(unified_dose, unified_dose=='5 MG + 5 MG', '0.01')
unified_dose <- replace(unified_dose, unified_dose=='20 MG + 25 MG', '0.045')
unified_dose <- replace(unified_dose, unified_dose=='10 MG + 12,5 MG', '0.0225')
unified_dose <- replace(unified_dose, unified_dose=='10 MG + 10 MG', '0.02')
unified_dose <- replace(unified_dose, unified_dose=='20 mg', '0.02')
unified_dose <- replace(unified_dose, unified_dose=='300 J./3 ML', '300')
unified_dose <- replace(unified_dose, unified_dose=='150 J.M./1,5 ML', '150')
unified_dose <- replace(unified_dose, unified_dose=='20 MG + 12,5 MG', '0.0325')
unified_dose <- replace(unified_dose, unified_dose=='0,75 G', '0.75')
unified_dose <- replace(unified_dose, unified_dose=='80 MG + 12,5 MG', '0.0925')
unified_dose <- replace(unified_dose, unified_dose=='0,16 g', '0.16')
unified_dose <- replace(unified_dose, unified_dose=='5 MG + 10 MG', '0.015')
unified_dose <- replace(unified_dose, unified_dose=='30 mg', '0.03')
unified_dose <- replace(unified_dose, unified_dose=='160 + 25 mg', '0.185')
unified_dose <- replace(unified_dose, unified_dose=='15 mg', '0.015')
unified_dose <- replace(unified_dose, unified_dose=='10 mg', '0.01')
unified_dose <- replace(unified_dose, unified_dose=='80 + 12,5 mg', '0.0925')
unified_dose <- replace(unified_dose, unified_dose=='5 mg', '0.005')
unified_dose <- replace(unified_dose, unified_dose=='40 mg', '0.04')
unified_dose <- replace(unified_dose, unified_dose=='30 mg', '0.03')
unified_dose <- replace(unified_dose, unified_dose=='320 MG + 25 MG', '0.345')
unified_dose <- replace(unified_dose, unified_dose=='10 MG + 2,5 MG', '0.0125')
unified_dose <- replace(unified_dose, unified_dose=='4 + 5mg', '0.009')
unified_dose <- replace(unified_dose, unified_dose=='8 + 5mg', '0.013')
unified_dose <- replace(unified_dose, unified_dose=='0,08 g', '0.08')
unified_dose <- replace(unified_dose, unified_dose=='8 + 10mg', '0.018')
unified_dose <- replace(unified_dose, unified_dose=='160 mg', '0.16')
unified_dose <- replace(unified_dose, unified_dose=='0,32 G', '0.32')
unified_dose <- replace(unified_dose, unified_dose=='160 + 12,5mg', '0.1725')
unified_dose <- replace(unified_dose, unified_dose=='0,095 G BURSZTYNIANU = 0,1 G WINIANU', '0.1')
unified_dose <- replace(unified_dose, unified_dose=='0,145 G', '0.145')
unified_dose <- replace(unified_dose, unified_dose=='0,00375 G', '0.00375')
unified_dose <- replace(unified_dose, unified_dose=='0,1425 G BURSZTYNIANU = 0,15 G WINIANU', '0.15')
unified_dose <- replace(unified_dose, unified_dose=='0,19 G BURSZTYNIANU = 0,2 G WINIANU', '0.2')
unified_dose <- replace(unified_dose, unified_dose=='160 + 12,5 mg', '0.1725')
unified_dose <- replace(unified_dose, unified_dose=='4 + 1,25 mg', '0.00525')
unified_dose <- replace(unified_dose, unified_dose=='4 + 10mg', '0.014')
unified_dose <- replace(unified_dose, unified_dose=='80 mg', '0.08')
unified_dose <- replace(unified_dose, unified_dose=='8 MG + 2,5 MG', '0.0105')
unified_dose <- replace(unified_dose, unified_dose=='100+12,5mg', '0.1125')
unified_dose <- replace(unified_dose, unified_dose=='0,6 MG/1 ML', '0.0006')
unified_dose <- replace(unified_dose, unified_dose=='400 J.M./10 ML', '0.400')
unified_dose <- replace(unified_dose, unified_dose=='0,04 G + 0,0125 G', '0.0525')
unified_dose <- replace(unified_dose, unified_dose=='320 MG + 12,5 MG', '0.3325')
unified_dose <- replace(unified_dose, unified_dose=='320 + 25 mg', '0.345')
unified_dose <- replace(unified_dose, unified_dose=='1000 J.M./10 ML', '1000')
unified_dose <- replace(unified_dose, unified_dose=='0,0125 G + 0,01 G', '0.0225')
unified_dose <- replace(unified_dose, unified_dose=='100 j/ml', '100')
unified_dose <- replace(unified_dose, unified_dose=='0,005 G/2 ML', '0.005')
unified_dose <- replace(unified_dose, unified_dose=='10 MG/160 MG/25 MG', '0.16')
unified_dose <- replace(unified_dose, unified_dose=='500 J.M./5 ML', '500')
unified_dose <- replace(unified_dose, unified_dose=='0,2 MG/2 ML', '0.0002')

df_right_age$Dawka <- unified_dose

# Write results to CSV file
write.csv(df_right_age, 'nasercowe_cleared.csv', row.names=FALSE, na='')
